---

- name: Set variable version of ip
  shell: echo $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
  register: ip_full_version


- name: Copy NGINX repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install packages 
  yum: 
    name: nginx
    state: latest
    update_cache: yes
  
- name: Copy NGINX default.conf
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  register: defaultconf

- name: Copy Gravitee constants.json
  template:
    src: constants.json
    dest: /opt/graviteeio-management-ui/constants.json
  register: constantsjson

- name: Copy Logo CVCCorp
  copy:
    src: CVCCorp_Logo.png
    dest: /opt/graviteeio-management-ui/themes/assets/GRAVITEE_LOGO1-01.png

- name: Systemd NGINX Started
  systemd:
    state: started
    name: nginx
    daemon_reload: yes
    enabled: yes

- name: Systemd NGINX Restart
  systemd:
    state: restarted
    name: nginx
    enabled: yes
  when: defaultconf.changed or constantsjson.changed